# Generated by Django 5.1.2 on 2024-10-15 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('best_seller', models.CharField(blank=True, choices=[('Акция', 'Акция'), ('Новинка', 'Новинка')], max_length=10, null=True)),
                ('area', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Площадь, м²')),
                ('floors', models.PositiveIntegerField()),
                ('rooms', models.PositiveIntegerField()),
                ('living_area', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Жилая площадь, м²')),
                ('bedrooms', models.PositiveIntegerField()),
                ('garage', models.BooleanField(default=False)),
                ('purpose', models.CharField(choices=[('Частный дом', 'Частный дом'), ('Коммерческая недвижимость', 'Коммерческая недвижимость')], max_length=30)),
                ('construction_technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.constructiontechnology')),
            ],
        ),
    ]
