# Generated by Django 5.1.2 on 2024-10-17 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_house_image_houseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество санузлов'),
        ),
        migrations.AddField(
            model_name='house',
            name='construction_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок строительства, дней'),
        ),
        migrations.AddField(
            model_name='house',
            name='garage_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Гараж (кол-во машин)'),
        ),
        migrations.AddField(
            model_name='house',
            name='warranty',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Гарантия, лет'),
        ),
        migrations.CreateModel(
            name='HouseFacadeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='houses/facades/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facade_images', to='backend.house')),
            ],
        ),
        migrations.CreateModel(
            name='HouseInteriorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='houses/interior/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interior_images', to='backend.house')),
            ],
        ),
        migrations.CreateModel(
            name='HouseLayoutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='houses/layouts/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_images', to='backend.house')),
            ],
        ),
    ]
