# Generated by Django 5.1.2 on 2024-10-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_house_bathrooms_house_construction_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='kitchen_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
