# Generated by Django 5.1.2 on 2024-10-17 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_house_kitchen_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='FinishingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_per_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за м²')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishing_options', to='backend.house')),
            ],
        ),
    ]
