# Generated by Django 5.1.2 on 2024-10-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_house_description_finishingoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishingoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='houses/finishing_options/', verbose_name='Изображение'),
        ),
    ]
