# Generated by Django 5.1.2 on 2024-10-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='user/reviews/'),
        ),
    ]
