# Generated by Django 5.1.2 on 2024-10-18 17:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_review_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('construction_place', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('finishing_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.finishingoption')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.house')),
            ],
        ),
    ]
