# Generated by Django 5.1.2 on 2024-10-19 20:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.house', verbose_name='Выбранный дом'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.house', verbose_name='Интересующий дом')),
            ],
        ),
    ]
