# Generated by Django 5.1.2 on 2024-10-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_order_house_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='UserQuestion',
        ),
    ]
