# Generated by Django 5.1.2 on 2024-10-21 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_rename_question_userquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(verbose_name='Дата покупки')),
                ('buyer_name', models.CharField(max_length=255, verbose_name='Имя покупателя')),
                ('buyer_phone', models.CharField(max_length=20, verbose_name='Номер телефона покупателя')),
                ('buyer_email', models.EmailField(max_length=255, verbose_name='Почта покупателя')),
                ('construction_status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Построен'), ('not_started', 'Не начато')], max_length=20, verbose_name='Статус строительства')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.house', verbose_name='Купленный дом')),
            ],
        ),
    ]
