# Generated by Django 5.1.2 on 2024-10-22 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_purchasedhouse_latitude_purchasedhouse_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='finishing_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.finishingoption'),
        ),
    ]
