# Generated by Django 5.1.2 on 2024-10-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_order_latitude_order_longitude_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='field',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
