# Generated by Django 5.1.2 on 2024-10-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_filter_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='field',
        ),
    ]
