# Generated by Django 5.1.2 on 2024-11-06 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_userquestion_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserQuestion',
            new_name='UserQuestionHouse',
        ),
    ]
