# Generated by Django 5.1.2 on 2024-11-06 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_rename_userquestion_userquestionhouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('waiting', 'Ожидает ответа'), ('answered', 'Ответ предоставлен'), ('closed', 'Закрыт')], default='waiting', max_length=10, verbose_name='Статус')),
            ],
        ),
    ]
