# Generated by Django 5.1.2 on 2024-11-09 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_userquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishingoption',
            name='house',
        ),
        migrations.CreateModel(
            name='HouseFinishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finishing_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.finishingoption')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.house')),
            ],
        ),
    ]
