# Generated by Django 5.1.2 on 2024-11-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_remove_finishingoption_house_housefinishing'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='finishing_options',
            field=models.ManyToManyField(related_name='houses', through='backend.HouseFinishing', to='backend.finishingoption'),
        ),
    ]
