# Generated by Django 5.1.2 on 2024-11-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_house_finishing_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='houseimage',
            name='house',
        ),
        migrations.RemoveField(
            model_name='houseinteriorimage',
            name='house',
        ),
        migrations.RemoveField(
            model_name='houselayoutimage',
            name='house',
        ),
        migrations.AddField(
            model_name='house',
            name='facade_images',
            field=models.ManyToManyField(blank=True, related_name='facade_houses', to='backend.image'),
        ),
        migrations.AddField(
            model_name='house',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='houses', to='backend.image'),
        ),
        migrations.AddField(
            model_name='house',
            name='interior_images',
            field=models.ManyToManyField(blank=True, related_name='interior_houses', to='backend.image'),
        ),
        migrations.AddField(
            model_name='house',
            name='layout_images',
            field=models.ManyToManyField(blank=True, related_name='layout_houses', to='backend.image'),
        ),
        migrations.DeleteModel(
            name='HouseFacadeImage',
        ),
        migrations.DeleteModel(
            name='HouseImage',
        ),
        migrations.DeleteModel(
            name='HouseInteriorImage',
        ),
        migrations.DeleteModel(
            name='HouseLayoutImage',
        ),
    ]
