# Generated by Django 5.1.2 on 2024-11-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_image_remove_houseimage_house_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housecategory',
            options={'verbose_name': 'Категория дома', 'verbose_name_plural': 'Категории домов'},
        ),
        migrations.AlterField(
            model_name='house',
            name='area',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=6, verbose_name='Площадь, м²'),
        ),
        migrations.AlterField(
            model_name='house',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Количество санузлов'),
        ),
        migrations.AlterField(
            model_name='house',
            name='bedrooms',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Количество спален'),
        ),
        migrations.AlterField(
            model_name='house',
            name='best_seller',
            field=models.CharField(blank=True, choices=[('Акция', 'Акция'), ('Новинка', 'Новинка')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='finishing_options',
            field=models.ManyToManyField(db_index=True, related_name='houses', through='backend.HouseFinishing', to='backend.finishingoption'),
        ),
        migrations.AlterField(
            model_name='house',
            name='floors',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Количество этажей'),
        ),
        migrations.AlterField(
            model_name='house',
            name='kitchen_area',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=6, null=True, verbose_name='Площадь кухни'),
        ),
        migrations.AlterField(
            model_name='house',
            name='living_area',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=6, verbose_name='Жилая площадь, м²'),
        ),
        migrations.AlterField(
            model_name='house',
            name='new',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Новый продукт'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='rooms',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='housecategory',
            index=models.Index(fields=['name'], name='backend_hou_name_70c218_idx'),
        ),
    ]
