# Generated by Django 5.1.3 on 2024-11-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_alter_housecategory_options_alter_house_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='house',
        ),
        migrations.AddField(
            model_name='house',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='houses', to='backend.document'),
        ),
    ]
