# Generated by Django 5.1.3 on 2024-11-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_remove_house_garage_capacity_alter_house_garage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='garage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Гараж (кол-во машин)'),
        ),
    ]
